export const GITHUB_API_URL = 'https://api.github.com/graphql';
export const GITHUB_PROFILE_URL = 'https://github.com/henriquecesp/';
export const LINKEDIN_PROFILE_URL = 'https://www.linkedin.com/in/henriquecesp/';
export const YOUTUBE_PROFILE_URL = 'https://www.youtube.com/HenriqueCesp';
export const INSTAGRAM_PROFILE_URL = 'https://www.instagram.com/henriquecesp/';
export const CONTACT_EMAIL = 'henriquecesps4@gmail.com';
export const WEBSITE_DOMAIN = 'https://henriquecesp.dev/';
export const WEBSITE_NAME = 'henriquecesp.dev';
export const WEBSITE_TITLE = 'HenriqueCesp - FullStack Dev';
export const GA_TRACKING_ID = 'G-RX2N9J7LJ7';
export const IS_PRODUCTION = process.env.NODE_ENV === 'production';
